# Generated by Django 2.2 on 2021-07-03 11:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(default=None, max_length=25)),
                ('email', models.EmailField(max_length=35)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=15, region=None)),
                ('account_no', models.IntegerField(primary_key=True, serialize=False)),
                ('ac_balance', models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True)),
                ('pan_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_time', models.DateTimeField(auto_now_add=True)),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True)),
                ('debit_ac', models.IntegerField()),
                ('credit_ac', models.IntegerField()),
            ],
        ),
    ]
